# Softmax Classification

실행을 위한 모듈 버전 변경

In [1]:
%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)

TensorFlow 1.x selected.
1.15.2


## 1. 전체 학습코드

In [2]:
import tensorflow as tf
import numpy as np

learning_rate = 0.01
training_cnt = 1000
display_step = 250

train_X = np.array([[2, 3, 1, 1], [4, 3, 2, 1], [4, 2, 5, 5], [2, 5, 2, 1], [6, 3, 1, 2], [5, 4, 4, 2] ])
train_Y = np.array([[0, 0, 1], [0, 0 ,1], [0, 1, 0], [0, 1, 0], [1, 0, 0 ], [1, 0 ,0]])

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])

W = tf.Variable(tf.random_normal([4, 3]), name='weight') 
b = tf.Variable(tf.random_normal([3]), name='bias')  

pred = tf.nn.softmax(tf.matmul(X ,W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(pred), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
op_train = optimizer.minimize(cost)

prediction = tf.argmax(pred, 1)
true_Y = tf.argmax(Y, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, true_Y), dtype=tf.float32))

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for epoch in range(training_cnt):
    r_cost, r_pred, rr_pred, t_y, r_a, _ = sess.run([cost, pred,prediction, true_Y, accuracy, op_train], 
                                                     feed_dict = {X: train_X, Y: train_Y})
    
    if (epoch+1) % display_step == 0:
        print('\n*****************running****************\n')
        print('Run_count :[{}] cost : [{:0.4f}] \npred : {} \npred_Y : {} \ntrue_Y : {} \naccuracy : {:.2%}% \
              ' .format( (epoch+1), r_cost, r_pred, rr_pred, t_y, r_a )
             )
 
print("\nOptimization Finished!") 


*****************running****************

Run_count :[250] cost : [0.5618] 
pred : [[0.07559501 0.51738805 0.407017  ]
 [0.41688603 0.12948312 0.4536308 ]
 [0.2763401  0.71902245 0.00463746]
 [0.0117505  0.59730816 0.3909413 ]
 [0.83557177 0.01416458 0.1502637 ]
 [0.5185577  0.20977247 0.27166983]] 
pred_Y : [1 2 1 1 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 83.33%%               

*****************running****************

Run_count :[500] cost : [0.4680] 
pred : [[0.09111174 0.4403068  0.4685814 ]
 [0.47746748 0.05982814 0.46270436]
 [0.13027312 0.86752456 0.00220222]
 [0.01490757 0.6186537  0.36643866]
 [0.83520746 0.00290679 0.16188581]
 [0.6206523  0.13654011 0.2428076 ]] 
pred_Y : [2 0 1 1 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 83.33%%               

*****************running****************

Run_count :[750] cost : [0.4198] 
pred : [[0.08841209 0.40280756 0.5087803 ]
 [0.48072064 0.03628159 0.48299778]
 [0.09769861 0.90104574 0.00125567]
 [0.01259918 0.66498715 0.32241362]
 [0.

## (1) 모델 구축(build graph)

In [3]:
import tensorflow as tf
import numpy as np

learning_rate = 0.01
training_cnt = 1000
display_step = 250

train_X = np.array([[2, 3, 1, 1], [4, 3, 2, 1], [4, 2, 5, 5], [2, 5, 2, 1], [6, 3, 1, 2], [5, 4, 4, 2] ])
train_Y = np.array([[0, 0, 1], [0, 0 ,1], [0, 1, 0], [0, 1, 0], [1, 0, 0 ], [1, 0 ,0]])

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])

W = tf.Variable(tf.random_normal([4, 3]), name='weight') 
b = tf.Variable(tf.random_normal([3]), name='bias')  

pred = tf.nn.softmax(tf.matmul(X ,W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(pred), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
op_train = optimizer.minimize(cost)

prediction = tf.argmax(pred, 1)
true_Y = tf.argmax(Y, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, true_Y), dtype=tf.float32))

### 1) 파라메터 값 설정
- 머신러닝을 위한 기초 파라메터
- learning_rate : 값이 너무 적으면 Train 되지 않을 수 있고, 값이 너무 크면 overshooting이 발생할 수 있다.
- training_cnt : data set에 대한 training 반복 횟수


In [4]:
# 파라메터값 설정
learning_rate = 0.01
training_cnt = 1000
display_step = 250  # 원하는 출력 위치 조정

#### 2) 트레이닝 데이터 변수 선언
- 입력으로 들어가는 x data(input 4개), y data(output 3개) 설정
- 레이블 데이터를 one-hot encoding 형태로 구성

In [5]:
train_X = np.array([[2, 3, 1, 1], [4, 3, 2, 1], [4, 2, 5, 5], [2, 5, 2, 1], [6, 3, 1, 2], [5, 4, 4, 2] ])
train_Y = np.array([[0, 0, 1], [0, 0 ,1], [0, 1, 0], [0, 1, 0], [1, 0, 0 ], [1, 0 ,0]])

### 3) tf graph input
- X : 들어오는 row는 정해진게 없고, column 은 4개 즉 입력변수 4개 
- Y : 들어오는 row는 정해진게 없고, column 은 3개 즉 output 3개
- matrix 사용 하기 때문에 입력 변수를 담는 placeholder 1개로 된다

In [6]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])

### 4) tf.random_normal
- bias, weight 초기값을 난수로 생성

In [7]:
W = tf.Variable(tf.random_normal([4, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

### 5) softmax 함수 사용
- 기존 pred 계산에 softmax 함수를 적용하여 출력값의 합이 항상 1이 되게 한다.

In [8]:
pred = tf.nn.softmax(tf.matmul(X ,W) + b)

### 6) cost function
- 교차 엔트로피(cross-entropy) 사용
- 예측값과 실제값 사이의 확률분포 차이 계산

In [9]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(pred), axis=1))

### 7) 학습
- 경사하강법 사용

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
op_train = optimizer.minimize(cost)

### 8) 학습된 예측 값을 확인
- 예측된 최대 값의 index 반환
- One-hot encoding 한 Y값도 최대값 1이 있는 index 반환

In [11]:
prediction = tf.argmax(pred, 1)
true_Y = tf.argmax(Y, 1)

### 9) 정확도
- accuracy를 계산하여 분류가 정확한지 확인
- 예측값과 실제 데이터의 일치 여부 계산 
- 아래 코드는 평균을 이용한 정확도 계산

In [12]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, true_Y), dtype=tf.float32))

## (2) 모델 실행(run/update)
- pred는 softmax 함수를 통해 0~1사이의 값으로 나온다
- pred_Y는 pred에서 나온 최대 예측값의 index 반환
- accuracy는 예측한 Y값이 실제 Y값과 얼마나 일치하는가

In [13]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for epoch in range(training_cnt):
    r_cost, r_pred,rr_pred, t_y, r_a, _ = sess.run([cost, pred,prediction, true_Y, accuracy, op_train], 
                                                     feed_dict = {X: train_X, Y: train_Y})
    
    if (epoch+1) % display_step == 0:
        print('\n*****************running****************\n')
        print('Run_count :[{}] cost : [{:0.4f}] \npred : {} \npred_Y : {} \ntrue_Y : {} \naccuracy : {:.2%}% \
              ' .format( (epoch+1), r_cost, r_pred, rr_pred, t_y, r_a )
             )
 
print("\nOptimization Finished!") 


*****************running****************

Run_count :[250] cost : [0.6765] 
pred : [[3.5840562e-01 2.0225555e-01 4.3933877e-01]
 [2.9678088e-01 1.4193828e-01 5.6128085e-01]
 [1.8219894e-01 8.1763816e-01 1.6290165e-04]
 [2.9537669e-01 2.6821047e-01 4.3641284e-01]
 [8.3568680e-01 1.7263085e-02 1.4705013e-01]
 [3.8196906e-01 4.6329182e-01 1.5473913e-01]] 
pred_Y : [2 2 1 2 0 1] 
true_Y : [2 2 1 1 0 0] 
accuracy : 66.67%%               

*****************running****************

Run_count :[500] cost : [0.4839] 
pred : [[2.6074770e-01 2.5939035e-01 4.7986192e-01]
 [3.2697907e-01 7.1273215e-02 6.0174775e-01]
 [1.8095531e-01 8.1888819e-01 1.5652925e-04]
 [1.2560798e-01 5.3667003e-01 3.3772203e-01]
 [8.5786366e-01 2.8485898e-03 1.3928768e-01]
 [5.0367922e-01 3.1908545e-01 1.7723536e-01]] 
pred_Y : [2 2 1 1 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 100.00%%               

*****************running****************

Run_count :[750] cost : [0.3979] 
pred : [[2.1136121e-01 2.6261425e-01 5.2602452

## 2. 기타 학습 방법
- 출력 Y를 one_hot 함수를 이용하여 encoding 한 후 학습
- one_hot으로 늘어난 차원을 reshape로 축소
- softmax_cross_entropy_with_logits 함수 이용

In [14]:
import tensorflow as tf
import numpy as np

learning_rate = 0.01
training_cnt = 1000
display_step = 250

train_X = np.array([[2, 3, 1, 1], [4, 3, 2, 1], [4, 2, 5, 5], [2, 5, 2, 1], [6, 3, 1, 2], [5, 4, 4, 2] ])
train_Y = np.array([[2], [2], [1], [1], [0], [0]])

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.int32, shape=[None, 1])

Y_1 = tf.one_hot(Y, 3)  
Y_2 = tf.reshape(Y_1, [-1, 3]) 

W = tf.Variable(tf.random_normal([4, 3]), name='weight') 
b = tf.Variable(tf.random_normal([3]), name='bias')  

logits = tf.matmul(X ,W) + b
pred = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits = logits, labels = Y_2)
cost = tf.reduce_mean(cost_i)

optimizer = tf.train.GradientDescentOptimizer(learning_rate)
op_train = optimizer.minimize(cost)

prediction = tf.argmax(pred, 1)
true_Y = tf.argmax(Y_2, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, true_Y), dtype=tf.float32))

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

r_Y, r_one_Y,r_one_Y2 = sess.run([Y, Y_1, Y_2 ], feed_dict = {X: train_X, Y: train_Y})
print('train_Y : {} \none_hot_Y: {} \none_hot_reshape_Y {} ' .format(r_Y, r_one_Y,r_one_Y2))

for epoch in range(training_cnt):
    r_cost, r_pred,rr_pred, t_y, r_a, _ = sess.run([cost, pred,prediction, true_Y, accuracy, op_train], 
                                                     feed_dict = {X: train_X, Y: train_Y})
    
    if (epoch+1) % display_step == 0:
        print('\n*****************running****************\n')
        print('Run_count :[{}] cost : [{:0.4f}] \npred : {} \npred_Y : {} \ntrue_Y : {} \naccuracy : {:.2%}% \
              ' .format( (epoch+1), r_cost, r_pred, rr_pred, t_y, r_a )
             )
 
print("\nOptimization Finished!") 

train_Y : [[2]
 [2]
 [1]
 [1]
 [0]
 [0]] 
one_hot_Y: [[[0. 0. 1.]]

 [[0. 0. 1.]]

 [[0. 1. 0.]]

 [[0. 1. 0.]]

 [[1. 0. 0.]]

 [[1. 0. 0.]]] 
one_hot_reshape_Y [[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]] 

*****************running****************

Run_count :[250] cost : [0.7381] 
pred : [[0.357889   0.4015609  0.24055007]
 [0.49397627 0.10338409 0.4026397 ]
 [0.08587125 0.90740037 0.00672845]
 [0.22462589 0.4006133  0.37476084]
 [0.7630619  0.10746899 0.12946919]
 [0.44412613 0.14144765 0.4144263 ]] 
pred_Y : [1 0 1 1 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 66.67%%               

*****************running****************

Run_count :[500] cost : [0.5812] 
pred : [[0.24477035 0.44439942 0.3108302 ]
 [0.489941   0.06341993 0.4466391 ]
 [0.11531295 0.8820708  0.00261629]
 [0.07937078 0.5804322  0.3401971 ]
 [0.81666327 0.02505284 0.15828395]
 [0.5269083  0.12057904 0.35251266]] 
pred_Y : [1 0 1 1 0 0] 
true_Y : [2 2 1 1 0 0] 
accuracy : 66.67%%            

### 1) 정수로들어온 클래스 one_hot encoding 하기
- 0,1,2,3,.... 의 정수 클래스를 one_hot 함수 사용하여 변경
- one_hot을 하면 차원이 +1 이 된다.
- reshape를 통해 차원을 다시 맞춰준다.

In [15]:
train_Y = np.array([[2], [2], [1], [1], [0], [0]])

Y_1 = tf.one_hot(Y, 3)  
Y_2 = tf.reshape(Y_1, [-1, 3]) 

### 2) cost 함수 사용
- softmax_cross_entropy_with_logits_v2 함수 이용
- softmax_cross_entropy_with_logits 함수의 업그레이드 버전
- one_hot encoding한 라벨값 사용

In [16]:
logits = tf.matmul(X ,W) + b
pred = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits = logits, labels = Y_2)
cost = tf.reduce_mean(cost_i)